services:
    web:
        image: ghcr.io/shopwarelabs/devcontainer/base-slim:8.3
        ports:
            - 8000:8000
            - 5173:5173
            - 9998:9998
            - 9999:9999
        environment:
            COMPOSER_ROOT_VERSION: 6.7.9999999-dev
            HOST: '0.0.0.0'
            APP_URL: http://localhost:8000
            DATABASE_URL: mysql://root:root@database/shopware
            MAILER_DSN: smtp://mailer:1025
            OPENSEARCH_URL: http://opensearch:9200
            ADMIN_OPENSEARCH_URL: http://opensearch:9200
        volumes:
            - .:/var/www/html
        depends_on:
            database:
                condition: service_healthy

    database:
        image: mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: shopware
        command:
            - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
            - --log_bin_trust_function_creators=1
            - --binlog_cache_size=16M
            - --key_buffer_size=0
            - --join_buffer_size=1024M
            - --innodb_log_file_size=128M
            - --innodb_buffer_pool_size=1024M
            - --innodb_buffer_pool_instances=1
            - --group_concat_max_len=320000
            - --default-time-zone=+00:00
            - --max_binlog_size=512M
            - --binlog_expire_logs_seconds=86400
        volumes:
            - db-data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-proot" ]
            start_interval: 3s
            interval: 5s
            timeout: 1s
            retries: 10

    adminer:
        image: adminer
        stop_signal: SIGKILL
        depends_on: [ database ]
        environment:
            ADMINER_DEFAULT_SERVER: database
        ports:
            - '9080:8080'

    valkey:
        image: valkey/valkey:alpine
        command: [ "--maxmemory-policy", "volatile-lfu", "--save", "", "--appendonly", "no" ]

    mailer:
        image: axllent/mailpit
        ports:
            - '8025:8025'

    opensearch:
        image: opensearchproject/opensearch:latest
        environment:
            OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'c3o_ZPHo!'
            discovery.type: single-node
            plugins.security.disabled: 'true'

volumes:
  db-data:
