shopware:
  feature:
    flags:
      - name: v6.5.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.6.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.7.0.0
        default: true
        major: true
        toggleable: false
      - name: v6.8.0.0
        default: false
        major: true
        toggleable: false
      - name: DISABLE_VUE_COMPAT
        default: true
        major: true
        toggleable: false
      - name: ACCESSIBILITY_TWEAKS
        default: true
        major: true
        toggleable: true
        description: "Accessibility tweaks (highly recommended)\nAccessibility improvements can alter the HTML and CSS structure of the template.\nThe accessibility improvements will be standard as of v6.7.0"
      - name: TELEMETRY_METRICS
        default: false
        major: false
        toggleable: true
        description: "Experimental! Enable OpenTelemetry metrics"
      - name: FLOW_EXECUTION_AFTER_BUSINESS_PROCESS
        default: false
        major: false
        toggleable: true
        description: "Experimental! Execute flows after the main unit of work has concluded"
      - name: PERFORMANCE_TWEAKS
        default: false
        major: false
        toggleable: true
        description: "Experimental! Contains Performance Tweaks for future changes"
      - name: CACHE_CONTEXT_HASH_RULES_OPTIMIZATION
        default: false
        major: false
        toggleable: true
        description: "Deprecated! Not used anymore, use the `CACHE_REWORK` feature flag instead."
      - name: CACHE_REWORK
        default: false
        major: false
        toggleable: true
        description: "Experimental! Enable new caching, includes following breaking changes: Only include rule ids which are relevant for different content in the HTTP cache context key; Remove cache states and cache pages for logged in customers or when the cart is filled by default; Enable caching for Store-API."
      - name: DEFERRED_CART_ERRORS
        default: false
        major: false
        toggleable: true
        description: "Defers cart errors that happen during SalesChannelContext creation\nThis feature will be standard as of v6.8.0"
      - name: PRODUCT_ANALYTICS
        default: false
        major: false
        toggleable: true
        description: "Experimental! Enables Product Analytics which collects usage data in the Administration."
      - name: REPEATED_PAYMENT_FINALIZE
        default: false
        major: true
        toggleable: true
        description: "This allows repeated calls to the /payment/finalize-transaction endpoint with the same token without throwing a 'token expired' exception."

      - name: METEOR_TEXT_EDITOR
        default: false
        major: false
        toggleable: true
        description: "Enables the Meteor text editor in the administration."