name: Prepare release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware'
    env:
      SHOPWARE_ADMIN_SKIP_SOURCEMAP_GENERATION: "1"
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/root
      COMPOSER_ROOT_VERSION: 6.7.9999999-dev
      APP_URL: http://localhost:8000
    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        options: '--mount="type=tmpfs,destination=/var/lib/mysql" --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=5s --health-timeout=2s --health-retries=3'
        ports:
          - "3306:3306"
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 4
        with:
          fetch-depth: "0"
          fetch-tags: "true"

      - name: Setup PHP
        uses: shivammathur/setup-php@6c489b2fc701c5f9ed70ccebe221b567bee578c0 # 2
        with:
          php-version: 8.2
          coverage: none
          extensions: gd, xml, dom, curl, pdo, mysqli, mbstring, pdo_mysql, bcmath

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # 4
        with:
          node-version: 22

      - name: build shopware
        run: |
          composer setup

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4
        with:
          name: context
          include-hidden-files: true
          path: |
            .
            !.git/config
            .github/
            !var/cache
            !tests/
            !public
            !**/node_modules
            !vendor
            !vendor-bin

  check-recipe:
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware' && github.ref_type == 'tag'
    env:
      GH_TOKEN: ${{ github.token }}
      CHECK_REPOSITORY: "shopware/recipes"
      CHECK_WORKFLOW: "nightly.yml"
      CHECK_STATUS: "success"
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 4
        with:
          fetch-depth: 0
      - name: Check whether the nightly workflow of the recipe repository is successful
        run: |
          bash .github/bin/check_workflow.bash "${CHECK_REPOSITORY}" "${CHECK_WORKFLOW}" "${CHECK_STATUS}"

  split:
    needs: build
    runs-on: ubuntu-24.04
    environment: ${{ format('manyrepos_{0}', github.ref_type) }}
    # we use this image to get an older git version, which does not suffer from a performance regression
    container: node:alpine3.19
    if: github.repository == 'shopware/shopware'
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        package:
          - administration
          - storefront
          - core
          - elasticsearch
    env:
      GIT_AUTHOR_EMAIL: "shopwarebot@shopware.com"
      GIT_AUTHOR_NAME: "shopwareBot"
      GIT_COMMITTER_EMAIL: "shopwarebot@shopware.com"
      GIT_COMMITTER_NAME: "shopwareBot"
      DEBUG: ${{ github.event.act && '1' || '' }}
    steps:
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # 4
        with:
          name: context

      - uses: shopware/octo-sts-action@main
        id: sts-shopware-split
        with:
          scope: shopware
          identity: ShopwareSplit

      - name: Is protected
        if: github.ref_protected
        run: echo 'is protected'

      - name: install deps
        run: apk add git git-subtree bash composer

      - name: Mark dir as safe
        run: git config --global --add safe.directory $PWD

      - name: split
        run: |
          bash .github/bin/split.bash split_repo "${{ matrix.package }}"
          git config --global --add safe.directory $PWD/repos/${{ matrix.package }}
          rm -Rf .git

      - name: Include assets
        run: |
          bash .github/bin/split.bash include_assets "${{ matrix.package }}"

      - name: Require core version
        run: |
          bash .github/bin/split.bash require_core_version "${{ matrix.package }}" "${{ github.ref_name }}" ${{ github.ref_type }}

      - name: Commit assets
        if: matrix.package != 'core'
        run: |
          bash .github/bin/split.bash commit "${{ matrix.package }}" "${{ github.ref_name }} (+ assets)"

      - name: Tag commit
        if: github.ref_type == 'tag'
        run: |
          bash .github/bin/split.bash tag "${{ matrix.package }}" "${{ github.ref_name }}"

      - name: Diff
        if: matrix.package != 'core'
        run: |
          cat repos/${{ matrix.package }}/composer.json
          git -C repos/${{ matrix.package }} log -n 2
          git -C repos/${{ matrix.package }} diff @^.. | head -n 100

      - name: Create temporary branch
        if: github.ref_type != 'tag' && !github.ref_protected
        run: |
          bash .github/bin/split.bash branch "${{ matrix.package }}" "tmp-${{ github.sha }}"

      - name: Create named branch
        if: github.ref_type != 'tag' && github.ref_protected
        run: |
          bash .github/bin/split.bash branch "${{ matrix.package }}" "${{ github.ref_name }}"

      - name: Push
        if: github.ref_type == 'tag' || github.ref_protected
        run: |
          bash .github/bin/split.bash push "${{ matrix.package }}" https://x-access-token:${{ steps.sts-shopware-split.outputs.token }}@github.com/shopware "${{ github.ref_name }}"

      - name: Push temporary branch
        if: github.ref_type != 'tag' && !github.ref_protected && !env.ACT
        run: |
          bash .github/bin/split.bash push "${{ matrix.package }}" https://x-access-token:${{ steps.sts-shopware-split.outputs.token }}@github.com/shopware "tmp-${{ github.sha }}"

  draft-release-notes:
    needs: split
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 4
        with:
          fetch-depth: 0
      - name: Draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # set dry run if it's not a tag
          DRY_RUN: ${{ github.ref_type != 'tag' && '1' || '' }}
        run: |
          echo DRY_RUN: "${DRY_RUN}"
          bash .github/bin/create_github_release.bash draft "${{ github.ref_name }}"

  create-sbp-release:
    needs: split
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware'
    strategy:
      matrix:
        sbp-environment: [STAGING, PRODUCTION]
    env:
      SBP_API_URL: ${{ secrets[format('SBP_API_URL_{0}', matrix.sbp-environment)] }}
      SBP_TOKEN: ${{ secrets[format('SBP_API_TOKEN_{0}', matrix.sbp-environment)] }}
      # set dry run if it's not a tag
      DRY_RUN: ${{ github.ref_type != 'tag' && '1' || '' }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 4
      - name: Create sbp release
        run: |
          echo DRY_RUN: "${DRY_RUN}"
          bash .github/bin/sbp_release.bash create "${{ github.ref_type == 'tag' && github.ref_name || 'v6.7.9999999.9999999-dev' }}"

  update-milestones:
    needs: split
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware' && github.ref_type == 'tag'
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 4
      - shell: bash
        run: npm ci --prefix .github/bin/js/
      - uses: actions/github-script@5c56fde4671bc2d3592fb0f2c5b5bab9ddae03b1 # 7
        env:
          TAG: ${{ github.ref_name }}
          DRY_RUN: ${{ vars.UPDATE_MILESTONES_DRY_RUN || 'true' }}
        with:
          script: |
            const { updateMilestonesOnRelease } = await import('${{ github.workspace }}/.github/bin/js/node_modules/@shopware-ag/gh-project-automation/dist/index.mjs')
            await updateMilestonesOnRelease({github, core, context, fetch})
